### ISSUE TITLE
Question on the uniqueness of generated token

### ISSUE THREAD

**Issue by motss** [nwoltman/uuid-token-generator#3]
Does one need to worry about the collision uniqueness of the tokens this package can generate? Wanting to use this to generate API keys for public use. Please advise.

**Comment by nwoltman** [comment]
Good thing you asked. There currently is a bug in the implementation that I haven't fixed yet that increases the chances of collisions. Please use my other package, [uid-generator](https://github.com/nwoltman/node-uid-generator), which does not have this bug.

**Comment by nwoltman** [comment]
Fixed in `v1.0.0` by 9b6748d201dfd1d5db502120903680dfeb2d26f8 (although I still recommend using [uid-generator](https://github.com/nwoltman/node-uid-generator) instead).
